### ISSUE TITLE
Can't install the font-manager through npm

### ISSUE THREAD

**Issue by AlexanderYW** [devongovett/font-manager#10]
Hey,
I get this error when i install the font-manager, am i missing something?

> 219 info install font-manager@0.2.1
> 220 verbose unsafe-perm in lifecycle true
> 221 info font-manager@0.2.1 Failed to exec install script
> 222 verbose unlock done using C:\Users\Alexander\AppData\Roaming\npm-cache_locks\font-manager-6db06e008ef16939.lock for C:\Electron\font\node_modules\font-manager
> 223 verbose stack Error: font-manager@0.2.1 install: `node-gyp rebuild`
> 223 verbose stack Exit status 1
> 223 verbose stack     at EventEmitter.<anonymous> (C:\Users\Alexander\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:212:16)
> 223 verbose stack     at emitTwo (events.js:100:13)
> 223 verbose stack     at EventEmitter.emit (events.js:185:7)
> 223 verbose stack     at ChildProcess.<anonymous> (C:\Users\Alexander\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:14:12)
> 223 verbose stack     at emitTwo (events.js:100:13)
> 223 verbose stack     at ChildProcess.emit (events.js:185:7)
> 223 verbose stack     at maybeClose (internal/child_process.js:821:16)
> 223 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 224 verbose pkgid font-manager@0.2.1
> 225 verbose cwd C:\Electron\font
> 226 error Windows_NT 10.0.10586
> 227 error argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Users\Alexander\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "font-manager"
> 228 error node v5.5.0
> 229 error npm  v2.1.18
> 230 error code ELIFECYCLE
> 231 error font-manager@0.2.1 install: `node-gyp rebuild`
> 231 error Exit status 1
> 232 error Failed at the font-manager@0.2.1 install script 'node-gyp rebuild'.
> 232 error This is most likely a problem with the font-manager package,
> 232 error not with npm itself.
> 232 error Tell the author that this fails on your system:
> 232 error     node-gyp rebuild
> 232 error You can get their info via:
> 232 error     npm owner ls font-manager
> 232 error There is likely additional logging output above.

**Comment by rBurgett** [comment]
@AlexanderYW - Do you have `node-gyp` installed globally on your system?

**Comment by AlexanderYW** [comment]
I had, but i figured it out after alot of work

I'm on windows so i had to set the settings for node vsbuild.exe to use the 2015 edition instead of 2012 or what default was, then i had to install the old python 2.7.x with the PATH setup correct, after all that i still got errors then i did a npm update -g which fixed everything

But thanks anyway! :)
