### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rensiu** [devongovett/font-manager#21]
Mac: When spellchecker and font-manager appear in the same process, electron crash!!!
Windows system is ok.

**Comment by robberfree** [comment]
@rensiu don't you have problem like this:
>Module not found: Can't resolve 'font-manager'

i have installed `font-manager` and rebuild it(with some warning).
my node version is 8.9.0.

**Comment by rensiu** [comment]
@robberfree your environment for example: browser?electron?webpack? and your configuration

**Comment by robberfree** [comment]
@rensiu 
i am creating a app use `React` and `Electron`.just use `Create React App` to manage the dependencies and other settings.

**Comment by rensiu** [comment]
@robberfree if you run 'npm start' and your other node packages can't be resolved, you can add `require('module').globalPaths.push(yourNodeModulesDir)` into your index.html.
try this and tell me result.

**Comment by robberfree** [comment]
@rensiu very sorry for replay lately.
Today I solved the problem with my colleague。
1.  I install `font-manager` to `devDependencies` wrongly in old days.Now I install it to `dependencies`
2. I use `electron-rebuild` to rebuild `font-manager` after read this document:[using-native-node-modules](https://electronjs.org/docs/tutorial/using-native-node-modules)

then I can require `font-manager` and use it in main process.
