### ISSUE TITLE
Add charset matching

### ISSUE THREAD

**Issue by sidorares** [devongovett/font-manager#6]
I'd like to use fontconfig to select nearest font that have some particular unicode characters in it ( for example, if I render big string of latin chars using Times face, and small substring is in arabic I'd prefer exact match for Times and any font with arabic glyphs for that small substring )

**Comment by devongovett** [comment]
Could you use the `substituteFont` method for this?

``` javascript
fontManager.substituteFontSync('Times', 'some characters');
```

**Comment by sidorares** [comment]
Thanks, that should work!
