### ISSUE TITLE
Library crashes when certain font present in Windows (screenshot provided)

### ISSUE THREAD

**Issue by rBurgett** [devongovett/font-manager#7]
I have been using this library on my system without trouble for a while, but I have had two client systems which the library refuses to run on. The problem is related to xfiles.ttf (http://cooltext.com/Download-Font-X-Files) which I found on both of their systems. If that font is present in Windows (both 32 and 64 bit), the library crashes. I recreated this on my system by running your tests successfully, then installing the font and running the tests again only to have them fail.

![screenshot 10](https://cloud.githubusercontent.com/assets/8548835/11752782/633e1b66-a00f-11e5-85cf-8b9f28adc158.png)

Do you have any idea why this would be happening? I need this fixed before I can send the application to anyone else. If this font crashes the library, I worry that other fonts might do the same. This font does not crash any other Windows applications that I can find. It only crashes this library.

Thanks!

**Comment by loilo** [comment]
+1 - same font file (xfiles.ttf), same problem.

**Comment by rBurgett** [comment]
@devongovett: A client has found two more fonts which cause font-manager to crash in Windows. And by crash I mean that it completely crashes Node. As result, I am disabling use of it in our application for the time being. Do you have any idea why font-manager crashes Node when it encounters certain fonts? Sorry, I can't get you copies of the two other fonts at the moment. But the [xfiles](http://cooltext.com/Download-Font-X-Files) font I shared above is still a working example... crashes it every time. Thanks for your time!

**Comment by devongovett** [comment]
@rBurgett this is all on Windows for you as well?

**Comment by rBurgett** [comment]
It crashes in Windows for me as well if I have that xfiles font installed. I don't have the two other fonts which I was told about yesterday. But just this morning as I was testing things, I installed that font and the tests crashed.

**Comment by rBurgett** [comment]
@devongovett I got my hands on another one of the trouble fonts. I tried to load it into OSX (in order to see if it crashes font-manager in OSX), but OSX won't let me. Apparently it is a bad font. You can see the message I got below:
![screen shot 2016-01-28 at 11 25 27 am](https://cloud.githubusercontent.com/assets/8548835/12654518/5d525d10-c5c2-11e5-9f03-616276392702.png)
So, apparently Windows allows folks to install bad fonts which OSX does not allow. But, unfortunately, I can't control whether or not my clients on Windows have any bad fonts installed.

**Comment by rBurgett** [comment]
Here is the font. OSX won't let me install it, but Windows installs it no problem.
[chimbari.ttf.zip](https://github.com/devongovett/font-manager/files/108653/chimbari.ttf.zip)

**Comment by devongovett** [comment]
Thanks. I'll look into this to see if we can't just ignore the bad fonts.

**Comment by rBurgett** [comment]
@devongovett That would be great! Thanks a lot.

**Comment by devongovett** [comment]
Should be fixed by ba3289d06cacecba6b070568c636a20e69c35dbf. Published to npm in v0.2.1.

Both of the fonts mentioned here have bad `name` tables. The crash resulted from some strings not existing in the font, but the node module attempting to read them anyway. Please let me know if you find more issues. Thanks!

**Comment by rBurgett** [comment]
@devongovett As far as I can tell, it works perfectly now... Thanks a lot! I can't tell you how much I appreciate it.

**Comment by loilo** [comment]
Love to hear that. Thank you!
