### ISSUE TITLE
search using list of families

### ISSUE THREAD

**Issue by sidorares** [devongovett/font-manager#8]
is it possible to use `findFont` or `findFonts` for list of families ( preferred first ) - similar to css?

I can call `findFont` multiple times but I can't find "relevance score" in the result to be able to pick up best matching font

**Comment by devongovett** [comment]
`findFont` always returns a result, even if it doesn't match exactly, but you could use `findFonts` for this instead, which returns an empty array if no fonts match the descriptor. You'll need to call it multiple times in your order of preference until the array is not empty.

**Comment by sidorares** [comment]
thanks @devongovett 
still not clear if possible to do the following:

input: list of families ( in preferred order )
result: first font that matches "well enough" any from input list. 

Unfortunately, because there is no score the only strategy would be to stop at first match.

Example input: Foobar, Verdana
Search for Foobar gives me '/System/Library/Fonts/Helvetica.dfont'
while search for Tahoma gives '/Library/Fonts/Tahoma.ttf'.
